In [6]:
#sort name for numpy while importing it
import numpy as np

val = [1,2,3,4,5]
#converting the list into numpy array
np_val = np.array(val)
print(np_val)
print(type(np_val))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#adding 2 to every element
np_val += 2
print(np_val)

[3 4 5 6 7]


In [12]:
#mean - finding missing values
print(np_val.mean())

5.0


In [14]:
np_val.sum()

25

In [23]:
list1 = [1,2,3,4]
list2 = [7,8,9,10]
list_combo = [list1,list2]
array_2d = np.array(list_combo)
array_2d

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

In [25]:
#array_2d = [[1,2,3,4],[5,6,7,8,9]]
print(array_2d.shape)
print(array_2d.sum())
print(array_2d.max())


(2, 4)
44
10


In [26]:
print(array_2d.max())
print(array_2d.min())
print(array_2d.mean())


10
1
5.5


In [27]:
array_2d.dtype


dtype('int32')

In [30]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [29]:
array_2d*2


array([[ 2,  4,  6,  8],
       [14, 16, 18, 20]])